name: "clean repo - images"

on:
  schedule:
    - cron: "0 1 1 * *" # Runs at 01:00, on day 1 of the month
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clean-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Call clean repo
      - name: Clean repo
        id: clean-repo-step
        uses: dotnet/docs-tools/cleanrepo@main
        with:
          function: "FindOrphanedImages"
          docfx_directory: "docs"
          target_directory: "docs"
          url_base_path: "/visualstudio"

      # Create the PR for the work done by the "clean repo" tool
      - name: create-pull-request
        uses: dotnet/actions-create-pull-request@v4
        with:
          branch: cleanrepo-orphaned-images
          title: "Monthly chores: Delete orphaned images"
          commit-message: "Bot ðŸ¤– generated CleanRepo tool run"
          body: "Find and delete orphaned images. Contributes to #..."
